# Generated by Django 5.0.6 on 2025-05-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
